[settings]
trusted_config_paths = [
  "~/Developer/projects",
  "~/Developer/repos",
]

[tools]
node = "lts"
python = "3.14"
go = "latest"
java = "openjdk-21"
gradle = "latest"
maven = "latest"
dotnet = "10.0"
